"""
Ghana High Schools List
Data source: https://www.kaggle.com/code/michaelaffare/ghana-high-technical-schools-exploration
"""

GHANA_HIGH_SCHOOLS = [
    # Greater Accra Region
    "Accra Academy",
    "Achimota School",
    "Armed Forces SHS",
    "Labone SHS",
    "Accra Girls' SHS",
    "Wesley Girls' High School",
    "Holy Trinity Cathedral SHS",
    "Kaneshie SHS",
    "Accra High School",
    "St. Thomas Aquinas SHS",
    "Tema SHS",
    "Tema Methodist Day SHS",
    "Tema Technical Institute",
    "Presbyterian Boys' SHS (PRESEC)",
    "Aburi Girls' SHS",
    "Pope John SHS and Minor Seminary",
    "St. John's Grammar School",
    "Madina SHS",
    "Kpone SHS",
    "Nungua SHS",
    "Teshie SHS",
    "Odorgonno SHS",
    "Dansoman SHS",
    "Gbawe Community SHS",
    "Haatso SHS",
    
    # Ashanti Region
    "Prempeh College",
    "Opoku Ware School",
    "Yaa Asantewaa Girls' SHS",
    "St. Louis SHS",
    "T.I. Ahmadiyya SHS",
    "Kumasi High School",
    "Kumasi Academy",
    "Kumasi Girls' SHS",
    "Kumasi SHS",
    "Osei Kyeretwie SHS",
    "Simms SHS",
    "Kumasi Anglican SHS",
    "Adventist SHS, Agona",
    "Konongo Odumase SHS",
    "Juaben SHS",
    "Bekwai SHS",
    "Offinso SHS",
    "Ejisu SHS",
    "Mampong Technical College",
    "Agogo State College",
    "Asante Mampong Methodist Girls' SHS",
    
    # Eastern Region
    "Koforidua SHS",
    "Koforidua SHTS",
    "Pope John SHS and Minor Seminary",
    "Aburi Girls' SHS",
    "Okuapeman SHS",
    "Akim Oda SHS",
    "Akim Tafo SHS",
    "Kibi Presbyterian SHS",
    "Mpraeso SHS",
    "Nkawkaw SHS",
    "Akro SHS",
    "Asuom SHS",
    "Nsutam Catholic SHS",
    "Akwatia SHS",
    "Suhum SHS",
    "Somanya SHS",
    "Krobo Girls' SHS",
    "Anum SHS",
    
    # Western Region
    "Mfantsipim School",
    "St. Augustine's College",
    "Holy Child School",
    "Ghana SHS",
    "Fijai SHS",
    "Sekondi College",
    "Takoradi SHS",
    "Takoradi Technical Institute",
    "Tarkwa SHS",
    "Prestea SHS",
    "Sefwi Wiawso SHS",
    "Bibiani SHS",
    "Asankragwa SHS",
    "Ahantaman Girls' SHS",
    "Shama SHS",
    "Effia-Kuma SHS",
    
    # Central Region
    "Adisadel College",
    "Wesley Girls' High School",
    "St. Augustine's College",
    "Mfantsipim School",
    "Holy Child School",
    "Ghana National College",
    "Aggrey Memorial SHS",
    "Swedru SHS",
    "Apam SHS",
    "Mankessim SHS",
    "Saltpond Methodist SHS",
    "Winneba SHS",
    "Komenda SHS",
    "Biriwa SHS",
    "Assin State College",
    "Assin Manso SHS",
    
    # Volta Region
    "Mawuli School",
    "Keta SHTS",
    "Kpando SHS",
    "Ho SHS",
    "Ho Technical Institute",
    "Hohoe E.P. SHS",
    "Hohoe Municipal Assembly SHS",
    "Anlo SHS",
    "Avenor SHS",
    "Sogakope SHS",
    "Tongu SHS",
    "Denu SHS",
    "Dzodze SHS",
    "Peki SHS",
    "Ve SHS",
    
    # Northern Region
    "Tamale SHS",
    "Tamale Girls' SHS",
    "Ghana SHS, Tamale",
    "Savelugu SHS",
    "Yendi SHS",
    "Bimbilla SHS",
    "Salaga SHS",
    "Tolon SHS",
    "Gushegu SHS",
    "Karaga SHS",
    "Zabzugu SHS",
    
    # Upper East Region
    "Bolgatanga SHS",
    "Bolgatanga Girls' SHS",
    "Navrongo SHS",
    "Zuarungu SHS",
    "Bongo SHS",
    "Paga SHS",
    "Sandema SHS",
    "Zebilla SHS",
    
    # Upper West Region
    "Wa SHS",
    "Wa T.I. Ahmadiyya SHS",
    "Jirapa SHS",
    "Lawra SHS",
    "Nadowli SHS",
    "Tumu SHS",
    
    # Brong Ahafo Region
    "Sunyani SHS",
    "Sunyani SHTS",
    "Bechem Presbyterian SHS",
    "Berekum SHS",
    "Dormaa SHS",
    "Wenchi Methodist SHS",
    "Techiman SHS",
    "Atebubu SHS",
    "Kintampo SHS",
    "Nkoranza SHS",
    "Drobo SHS",
    "Duayaw Nkwanta SHS",
    
    # Other Notable Schools
    "Achimota School",
    "Mfantsipim School",
    "Wesley Girls' High School",
    "Prempeh College",
    "Opoku Ware School",
    "St. Augustine's College",
    "Adisadel College",
    "Holy Child School",
    "Yaa Asantewaa Girls' SHS",
    "Aburi Girls' SHS",
    "Presbyterian Boys' SHS (PRESEC)",
    "St. Louis SHS",
    "Ghana National College",
    "Mawuli School",
    "Keta SHTS",
    "T.I. Ahmadiyya SHS",
    
    # Additional Schools
    "Other (Not Listed)",
]

# Remove duplicates and sort
GHANA_HIGH_SCHOOLS = sorted(list(set(GHANA_HIGH_SCHOOLS)))
