# Generated by Django 5.2.4 on 2025-10-04 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_science', 'General Science'), ('general_arts', 'General Arts'), ('business', 'Business'), ('visual_arts', 'Visual Arts'), ('home_economics', 'Home Economics'), ('agricultural_science', 'Agricultural Science')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_school', models.CharField(max_length=200)),
                ('wassce_year', models.IntegerField()),
                ('index_number', models.CharField(max_length=20, unique=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('current_grade', models.CharField(blank=True, max_length=2)),
                ('target_grade', models.CharField(max_length=2)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
