# Generated by Django 5.0.1 on 2025-12-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_assignment_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_course_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
