# Generated by Django 5.0.1 on 2025-12-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_email_announcements_and_more'),
        ('students', '0002_update_previous_school_field'),
    ]

    operations = [
    ]
