# Generated by Django 5.2.4 on 2025-10-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_type', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='programme',
        ),
        migrations.CreateModel(
            name='ProgrammeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_subjects', to='students.programme')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_subjects', to='courses.subject')),
            ],
            options={
                'ordering': ['programme', 'subject__subject_type', 'order'],
                'unique_together': {('programme', 'subject')},
            },
        ),
    ]
